import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import Providers from "../components/Providers";
import { CartProvider } from "../context/CartContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NextMart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen `}
      >
        
        
          <Providers>
          <CartProvider>
            <Navbar></Navbar>
          <div className="bg-gradient-to-r from-gray-50 to-cyan-50">
    <main className="flex-1 mx-auto  max-w-7xl px-4 ">{children}</main>
        </div>
          </CartProvider>
        </Providers>
       
        
              <Footer></Footer>

      </body>
    </html>
  );
}
